/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AgendaRouteImport } from './routes/agenda'
import { Route as ChangesRouteImport } from './routes/changes'
import { Route as CompanyRouteImport } from './routes/company'
import { Route as DraftsRouteImport } from './routes/drafts'
import { Route as HelpRouteImport } from './routes/help'
import { Route as ScheduleRouteImport } from './routes/schedule'
import { Route as DraftsIndexRouteImport } from './routes/drafts.index'
import { Route as DraftsCodeRouteImport } from './routes/drafts.$code'
import { Route as MeetingsIndexRouteImport } from './routes/meetings.index'
import { Route as MeetingsMeetingSlugRouteImport } from './routes/meetings.$meetingSlug'
import { Route as RoomsIndexRouteImport } from './routes/rooms.index'
import { Route as RoomsRoomIdRouteImport } from './routes/rooms.$roomId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendaRoute = AgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangesRoute = ChangesRouteImport.update({
  id: '/changes',
  path: '/changes',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyRoute = CompanyRouteImport.update({
  id: '/company',
  path: '/company',
  getParentRoute: () => rootRouteImport,
} as any)
const DraftsRoute = DraftsRouteImport.update({
  id: '/drafts',
  path: '/drafts',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const ScheduleRoute = ScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const DraftsIndexRoute = DraftsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DraftsRoute,
} as any)
const DraftsCodeRoute = DraftsCodeRouteImport.update({
  id: '/$code',
  path: '/$code',
  getParentRoute: () => DraftsRoute,
} as any)
const MeetingsIndexRoute = MeetingsIndexRouteImport.update({
  id: '/meetings/',
  path: '/meetings/',
  getParentRoute: () => rootRouteImport,
} as any)
const MeetingsMeetingSlugRoute = MeetingsMeetingSlugRouteImport.update({
  id: '/meetings/$meetingSlug',
  path: '/meetings/$meetingSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomsIndexRoute = RoomsIndexRouteImport.update({
  id: '/rooms/',
  path: '/rooms/',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomsRoomIdRoute = RoomsRoomIdRouteImport.update({
  id: '/rooms/$roomId',
  path: '/rooms/$roomId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/agenda': typeof AgendaRoute
  '/changes': typeof ChangesRoute
  '/company': typeof CompanyRoute
  '/drafts': typeof DraftsRouteWithChildren
  '/help': typeof HelpRoute
  '/schedule': typeof ScheduleRoute
  '/drafts/$code': typeof DraftsCodeRoute
  '/meetings/$meetingSlug': typeof MeetingsMeetingSlugRoute
  '/rooms/$roomId': typeof RoomsRoomIdRoute
  '/drafts/': typeof DraftsIndexRoute
  '/meetings/': typeof MeetingsIndexRoute
  '/rooms/': typeof RoomsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/agenda': typeof AgendaRoute
  '/changes': typeof ChangesRoute
  '/company': typeof CompanyRoute
  '/help': typeof HelpRoute
  '/schedule': typeof ScheduleRoute
  '/drafts/$code': typeof DraftsCodeRoute
  '/meetings/$meetingSlug': typeof MeetingsMeetingSlugRoute
  '/rooms/$roomId': typeof RoomsRoomIdRoute
  '/drafts': typeof DraftsIndexRoute
  '/meetings': typeof MeetingsIndexRoute
  '/rooms': typeof RoomsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/agenda': typeof AgendaRoute
  '/changes': typeof ChangesRoute
  '/company': typeof CompanyRoute
  '/drafts': typeof DraftsRouteWithChildren
  '/help': typeof HelpRoute
  '/schedule': typeof ScheduleRoute
  '/drafts/$code': typeof DraftsCodeRoute
  '/meetings/$meetingSlug': typeof MeetingsMeetingSlugRoute
  '/rooms/$roomId': typeof RoomsRoomIdRoute
  '/drafts/': typeof DraftsIndexRoute
  '/meetings/': typeof MeetingsIndexRoute
  '/rooms/': typeof RoomsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/agenda'
    | '/changes'
    | '/company'
    | '/drafts'
    | '/help'
    | '/schedule'
    | '/drafts/$code'
    | '/meetings/$meetingSlug'
    | '/rooms/$roomId'
    | '/drafts/'
    | '/meetings/'
    | '/rooms/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/agenda'
    | '/changes'
    | '/company'
    | '/help'
    | '/schedule'
    | '/drafts/$code'
    | '/meetings/$meetingSlug'
    | '/rooms/$roomId'
    | '/drafts'
    | '/meetings'
    | '/rooms'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/agenda'
    | '/changes'
    | '/company'
    | '/drafts'
    | '/help'
    | '/schedule'
    | '/drafts/$code'
    | '/meetings/$meetingSlug'
    | '/rooms/$roomId'
    | '/drafts/'
    | '/meetings/'
    | '/rooms/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AgendaRoute: typeof AgendaRoute
  ChangesRoute: typeof ChangesRoute
  CompanyRoute: typeof CompanyRoute
  DraftsRoute: typeof DraftsRouteWithChildren
  HelpRoute: typeof HelpRoute
  ScheduleRoute: typeof ScheduleRoute
  MeetingsMeetingSlugRoute: typeof MeetingsMeetingSlugRoute
  RoomsRoomIdRoute: typeof RoomsRoomIdRoute
  MeetingsIndexRoute: typeof MeetingsIndexRoute
  RoomsIndexRoute: typeof RoomsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenda': {
      id: '/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AgendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changes': {
      id: '/changes'
      path: '/changes'
      fullPath: '/changes'
      preLoaderRoute: typeof ChangesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company': {
      id: '/company'
      path: '/company'
      fullPath: '/company'
      preLoaderRoute: typeof CompanyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drafts': {
      id: '/drafts'
      path: '/drafts'
      fullPath: '/drafts'
      preLoaderRoute: typeof DraftsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedule': {
      id: '/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof ScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drafts/': {
      id: '/drafts/'
      path: '/'
      fullPath: '/drafts/'
      preLoaderRoute: typeof DraftsIndexRouteImport
      parentRoute: typeof DraftsRoute
    }
    '/drafts/$code': {
      id: '/drafts/$code'
      path: '/$code'
      fullPath: '/drafts/$code'
      preLoaderRoute: typeof DraftsCodeRouteImport
      parentRoute: typeof DraftsRoute
    }
    '/meetings/': {
      id: '/meetings/'
      path: '/meetings'
      fullPath: '/meetings/'
      preLoaderRoute: typeof MeetingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meetings/$meetingSlug': {
      id: '/meetings/$meetingSlug'
      path: '/meetings/$meetingSlug'
      fullPath: '/meetings/$meetingSlug'
      preLoaderRoute: typeof MeetingsMeetingSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rooms/': {
      id: '/rooms/'
      path: '/rooms'
      fullPath: '/rooms/'
      preLoaderRoute: typeof RoomsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rooms/$roomId': {
      id: '/rooms/$roomId'
      path: '/rooms/$roomId'
      fullPath: '/rooms/$roomId'
      preLoaderRoute: typeof RoomsRoomIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DraftsRouteChildren {
  DraftsCodeRoute: typeof DraftsCodeRoute
  DraftsIndexRoute: typeof DraftsIndexRoute
}

const DraftsRouteChildren: DraftsRouteChildren = {
  DraftsCodeRoute: DraftsCodeRoute,
  DraftsIndexRoute: DraftsIndexRoute,
}

const DraftsRouteWithChildren =
  DraftsRoute._addFileChildren(DraftsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AgendaRoute: AgendaRoute,
  ChangesRoute: ChangesRoute,
  CompanyRoute: CompanyRoute,
  DraftsRoute: DraftsRouteWithChildren,
  HelpRoute: HelpRoute,
  ScheduleRoute: ScheduleRoute,
  MeetingsMeetingSlugRoute: MeetingsMeetingSlugRoute,
  RoomsRoomIdRoute: RoomsRoomIdRoute,
  MeetingsIndexRoute: MeetingsIndexRoute,
  RoomsIndexRoute: RoomsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
